#%%
import pandas as pd 

chart_key = "oz-datablogs-something_random"
fillo = 'https://vaccinedata.covid19nearme.com.au/data/distribution.json'

#%%
df = pd.read_json(fillo)

# 'DATE_AS_AT', 'STATE_CLINICS_VIC_DISTRIBUTED',
#        'STATE_CLINICS_QLD_DISTRIBUTED', 'STATE_CLINICS_WA_DISTRIBUTED',
#        'STATE_CLINICS_TAS_DISTRIBUTED', 'STATE_CLINICS_SA_DISTRIBUTED',
#        'STATE_CLINICS_ACT_DISTRIBUTED', 'STATE_CLINICS_NT_DISTRIBUTED',
#        'STATE_CLINICS_NSW_DISTRIBUTED', 'CWTH_AGED_CARE_DISTRIBUTED',
#        'CWTH_PRIMARY_CARE_DISTRIBUTED', 'STATE_CLINICS_VIC_AVAILABLE',
#        'STATE_CLINICS_QLD_AVAILABLE', 'STATE_CLINICS_WA_AVAILABLE',
#        'STATE_CLINICS_TAS_AVAILABLE', 'STATE_CLINICS_SA_AVAILABLE',
#        'STATE_CLINICS_ACT_AVAILABLE', 'STATE_CLINICS_NT_AVAILABLE',
#        'STATE_CLINICS_NSW_AVAILABLE', 'CWTH_AGED_CARE_AVAILABLE',
#        'CWTH_PRIMARY_CARE_AVAILABLE', 'STATE_CLINICS_VIC_ADMINISTERED',
#        'STATE_CLINICS_QLD_ADMINISTERED', 'STATE_CLINICS_WA_ADMINISTERED',
#        'STATE_CLINICS_TAS_ADMINISTERED', 'STATE_CLINICS_SA_ADMINISTERED',
#        'STATE_CLINICS_ACT_ADMINISTERED', 'STATE_CLINICS_NT_ADMINISTERED',
#        'STATE_CLINICS_NSW_ADMINISTERED', 'CWTH_AGED_CARE_ADMINISTERED',
#        'CWTH_PRIMARY_CARE_ADMINISTERED',
#        'STATE_CLINICS_VIC_AVAILABLE_MINUS_ADMINISTERED',
#        'STATE_CLINICS_QLD_AVAILABLE_MINUS_ADMINISTERED',
#        'STATE_CLINICS_WA_AVAILABLE_MINUS_ADMINISTERED',
#        'STATE_CLINICS_TAS_AVAILABLE_MINUS_ADMINISTERED',
#        'STATE_CLINICS_SA_AVAILABLE_MINUS_ADMINISTERED',
#        'STATE_CLINICS_ACT_AVAILABLE_MINUS_ADMINISTERED',
#        'STATE_CLINICS_NT_AVAILABLE_MINUS_ADMINISTERED',
#        'STATE_CLINICS_NSW_AVAILABLE_MINUS_ADMINISTERED',
#        'CWTH_PRIMARY_CARE_AVAILABLE_MINUS_ADMINISTERED',
#        'STATE_CLINICS_VIC_ESTIMATED_DOSE_UTILISATION',
#        'STATE_CLINICS_QLD_ESTIMATED_DOSE_UTILISATION',
#        'STATE_CLINICS_WA_ESTIMATED_DOSE_UTILISATION',
#        'STATE_CLINICS_TAS_ESTIMATED_DOSE_UTILISATION',
#        'STATE_CLINICS_SA_ESTIMATED_DOSE_UTILISATION',
#        'STATE_CLINICS_ACT_ESTIMATED_DOSE_UTILISATION',
#        'STATE_CLINICS_NT_ESTIMATED_DOSE_UTILISATION',
#        'STATE_CLINICS_NSW_ESTIMATED_DOSE_UTILISATION',
#        'CWTH_AGED_CARE_ESTIMATED_DOSE_UTILISATION',
#        'CWTH_PRIMARY_CARE_ESTIMATED_DOSE_UTILISATION', 'VALIDATED', 'URL',
#        'CWTH_AGED_CARE_AVAILABLE_MINUS_ADMINISTERED'

df = df[['DATE_AS_AT','STATE_CLINICS_NSW_DISTRIBUTED','STATE_CLINICS_NSW_AVAILABLE','STATE_CLINICS_NSW_ADMINISTERED',
'STATE_CLINICS_NSW_ESTIMATED_DOSE_UTILISATION', 'STATE_CLINICS_NSW_AVAILABLE_MINUS_ADMINISTERED']]

print(df)
print(df.columns)


#%%