#%%

import pandas as pd 
import datetime
from yachtcharter import yachtCharter
chart_key = f"oz-covid-indigenous_vs_non_indigenous_vax_rates"

fillo = 'https://vaccinedata.covid19nearme.com.au/data/all.csv'

#%%

### THESE ARE 12+ POPULATIONS, AS USED IN OUR SPREADSHEET
# https://docs.google.com/spreadsheets/d/1cR0XSzndyV7J4IbNzvnKBK2diuOB6Bo0FUBzztcPlCk/edit#gid=71499319
pops = {"indig":591170, 'non_indig': 21272779}

df = pd.read_csv(fillo)

# 'FIRST_NATIONS_VIC_FIRST_DOSE_TOTAL', 'FIRST_NATIONS_VIC_SECOND_DOSE_TOTAL', 'FIRST_NATIONS_QLD_FIRST_DOSE_TOTAL',
# 'FIRST_NATIONS_QLD_SECOND_DOSE_TOTAL', 'FIRST_NATIONS_WA_FIRST_DOSE_TOTAL', 'FIRST_NATIONS_WA_SECOND_DOSE_TOTAL',
# 'FIRST_NATIONS_TAS_FIRST_DOSE_TOTAL', 'FIRST_NATIONS_TAS_SECOND_DOSE_TOTAL', 'FIRST_NATIONS_SA_FIRST_DOSE_TOTAL', 
# 'FIRST_NATIONS_SA_SECOND_DOSE_TOTAL', 'FIRST_NATIONS_ACT_FIRST_DOSE_TOTAL', 'FIRST_NATIONS_ACT_SECOND_DOSE_TOTAL',
# 'FIRST_NATIONS_NT_FIRST_DOSE_TOTAL', 'FIRST_NATIONS_NT_SECOND_DOSE_TOTAL', 'FIRST_NATIONS_NSW_FIRST_DOSE_TOTAL',
# 'FIRST_NATIONS_NSW_SECOND_DOSE_TOTAL', 'FIRST_NATIONS_AUS_FIRST_DOSE_TOTAL', 'FIRST_NATIONS_AUS_SECOND_DOSE_TOTAL',
# 'FIRST_NATIONS_VIC_FIRST_PCT_TOTAL', 'FIRST_NATIONS_VIC_SECOND_PCT_TOTAL', 'FIRST_NATIONS_QLD_FIRST_PCT_TOTAL',
# 'FIRST_NATIONS_QLD_SECOND_PCT_TOTAL', 'FIRST_NATIONS_WA_FIRST_PCT_TOTAL', 'FIRST_NATIONS_WA_SECOND_PCT_TOTAL',
# 'FIRST_NATIONS_TAS_FIRST_PCT_TOTAL', 'FIRST_NATIONS_TAS_SECOND_PCT_TOTAL', 'FIRST_NATIONS_SA_FIRST_PCT_TOTAL',
# 'FIRST_NATIONS_SA_SECOND_PCT_TOTAL', 'FIRST_NATIONS_ACT_FIRST_PCT_TOTAL', 'FIRST_NATIONS_ACT_SECOND_PCT_TOTAL',
# 'FIRST_NATIONS_NT_FIRST_PCT_TOTAL', 'FIRST_NATIONS_NT_SECOND_PCT_TOTAL', 'FIRST_NATIONS_NSW_FIRST_PCT_TOTAL', 
# 'FIRST_NATIONS_NSW_SECOND_PCT_TOTAL', 'FIRST_NATIONS_AUS_FIRST_PCT_TOTAL', 'FIRST_NATIONS_AUS_SECOND_PCT_TOTAL'


cols = [x for x in df.columns.tolist() if "FIRST_NATIONS" in x]

p = cols

print(p)
# print(p.columns.tolist())